### ISSUE TITLE
Update DNS plugin instructions

### ISSUE THREAD

**Issue by bmw** [certbot/website#353]
Most of the major DNS plugins are now available on:

- [ ] All versions of Debian except Jessie and Wheezy (see #351)
- [ ] All versions of Ubuntu (see #341)
- [ ] FreeBSD
- [ ] All versions of Devuan except Jessie (see #352)

We should update our instructions to reflect this.

**Comment by bmw** [comment]
After resolving this, we should update Erica's post at https://community.letsencrypt.org/t/getting-wildcard-certificates-with-certbot/56285.

**Comment by bmw** [comment]
To expand a bit more on this, the change we need to make here is we need to set the `dns_plugins` variable in `_scripts/instruction-widget/install.js` to `true` on these systems which will change which text from `_scripts/instruction-widget/templates/install/dnsplugins.html` is used.

One potential problem here is not all of the DNS plugins are packaged in the Debian based distros, however, many of them are and especially our more popular DNS plugins. For this reason, I think just flipping the variable here is a positive change, however, a more correct solution might be to explain this situation and tell people that they can still use Docker if the DNS plugin isn't available on their system.
